name: CI Pipeline

on:
  push:
    branches: [main, nrodrigues-test]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Make run.sh executable
        run: chmod +x ./run.sh

      - name: Execute run.sh
        run: ./run.sh

      - name: Upload results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results/
